### ISSUE TITLE
New version throws "Uncaught ReflectionException: Class \Bladerunner\blade does not exist"

### ISSUE THREAD

**Issue by luishdz1010** [ekandreas/bladerunner#86]
Linux
PHP 7.4
Installed via Composer 1.x ( iluminate/view version is v8.29.0).

Stacktrace:

```
Fatal error: Uncaught ReflectionException: Class \Bladerunner\blade does not exist in /path/to/project/vendor/illuminate/container/Container.php:830
Stack trace:
#0 /path/to/project/vendor/illuminate/container/Container.php(830): ReflectionClass->__construct()
#1 /path/to/project/vendor/illuminate/container/Container.php(712): Illuminate\Container\Container->build()
#2 /path/to/project/vendor/illuminate/container/Container.php(651): Illuminate\Container\Container->resolve()
#3 /path/to/project/web/app/plugins/bladerunner/src/Container.php(25): Illuminate\Container\Container->make()
#4 /path/to/project/web/app/plugins/bladerunner/globals/setup.php(40): Bladerunner\Container::current()
#5 /path/to/project/web/wp/wp-includes/class-wp-hook.php(287): WP_CLI\Runner->{closure}()
#6 /path/to/project/web/wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#7 /ho in /path/to/project/vendor/illuminate/container/Container.php on line 832
```

This happens during init making any route or even wp-cli fail.

**Comment by ekandreas** [comment]
Hi!
This is a deprecated package. Please use https://github.com/EFTEC/BladeOne instead!
